spring:
  application:
    name: grpc-client
  main:
    allow-bean-definition-overriding: true

grpc-stub:
  host-name: localhost
  port: 9009

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: "/api/v1"
  port: 9090
  http2:
    enabled: true




