spring:
  application:
    name: eureka-server

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    fetchRegistry: false
    registerWithEureka: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
