version: '3.7'

services:
  grpc-postgres:
    container_name: grpc_postgres
    image: postgres
    volumes:
      - ../volumes/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grpc_db
    ports:
      - "5432:5432"