spring:
  application:
    name: grpc-application
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/grpc_db
    username: postgres
    password: postgres

server:
  port: 8081
  servlet:
    context-path: "/api/v1"



kafka-config:
  bootstrap-server: http://localhost:9092
  acks: all

grpc:
  port: 9009

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/



