spring:
  application:
    name: grpc-server-application
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/grpc_db
    username: postgres
    password: postgres

server:
  port: 8081
  servlet:
    context-path: "/api/v1"


